//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Runbow.TWS.Web.sfservice {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://service.expressservice.integration.sf.com/", ConfigurationName="sfservice.IService")]
    public interface IService {
        
        // CODEGEN: 命名空间  的元素名称 arg0 以后生成的消息协定未标记为 nillable
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        Runbow.TWS.Web.sfservice.sfexpressServiceResponse sfexpressService(Runbow.TWS.Web.sfservice.sfexpressService request);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        System.Threading.Tasks.Task<Runbow.TWS.Web.sfservice.sfexpressServiceResponse> sfexpressServiceAsync(Runbow.TWS.Web.sfservice.sfexpressService request);
        
        // CODEGEN: 命名空间  的元素名称 arg0 以后生成的消息协定未标记为 nillable
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        Runbow.TWS.Web.sfservice.expressServiceForRouteLabelResponse expressServiceForRouteLabel(Runbow.TWS.Web.sfservice.expressServiceForRouteLabel request);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        System.Threading.Tasks.Task<Runbow.TWS.Web.sfservice.expressServiceForRouteLabelResponse> expressServiceForRouteLabelAsync(Runbow.TWS.Web.sfservice.expressServiceForRouteLabel request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class sfexpressService {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="sfexpressService", Namespace="http://service.expressservice.integration.sf.com/", Order=0)]
        public Runbow.TWS.Web.sfservice.sfexpressServiceBody Body;
        
        public sfexpressService() {
        }
        
        public sfexpressService(Runbow.TWS.Web.sfservice.sfexpressServiceBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="")]
    public partial class sfexpressServiceBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string arg0;
        
        public sfexpressServiceBody() {
        }
        
        public sfexpressServiceBody(string arg0) {
            this.arg0 = arg0;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class sfexpressServiceResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="sfexpressServiceResponse", Namespace="http://service.expressservice.integration.sf.com/", Order=0)]
        public Runbow.TWS.Web.sfservice.sfexpressServiceResponseBody Body;
        
        public sfexpressServiceResponse() {
        }
        
        public sfexpressServiceResponse(Runbow.TWS.Web.sfservice.sfexpressServiceResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="")]
    public partial class sfexpressServiceResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string @return;
        
        public sfexpressServiceResponseBody() {
        }
        
        public sfexpressServiceResponseBody(string @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class expressServiceForRouteLabel {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="expressServiceForRouteLabel", Namespace="http://service.expressservice.integration.sf.com/", Order=0)]
        public Runbow.TWS.Web.sfservice.expressServiceForRouteLabelBody Body;
        
        public expressServiceForRouteLabel() {
        }
        
        public expressServiceForRouteLabel(Runbow.TWS.Web.sfservice.expressServiceForRouteLabelBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="")]
    public partial class expressServiceForRouteLabelBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string arg0;
        
        public expressServiceForRouteLabelBody() {
        }
        
        public expressServiceForRouteLabelBody(string arg0) {
            this.arg0 = arg0;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class expressServiceForRouteLabelResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="expressServiceForRouteLabelResponse", Namespace="http://service.expressservice.integration.sf.com/", Order=0)]
        public Runbow.TWS.Web.sfservice.expressServiceForRouteLabelResponseBody Body;
        
        public expressServiceForRouteLabelResponse() {
        }
        
        public expressServiceForRouteLabelResponse(Runbow.TWS.Web.sfservice.expressServiceForRouteLabelResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="")]
    public partial class expressServiceForRouteLabelResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string @return;
        
        public expressServiceForRouteLabelResponseBody() {
        }
        
        public expressServiceForRouteLabelResponseBody(string @return) {
            this.@return = @return;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IServiceChannel : Runbow.TWS.Web.sfservice.IService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ServiceClient : System.ServiceModel.ClientBase<Runbow.TWS.Web.sfservice.IService>, Runbow.TWS.Web.sfservice.IService {
        
        public ServiceClient() {
        }
        
        public ServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Runbow.TWS.Web.sfservice.sfexpressServiceResponse Runbow.TWS.Web.sfservice.IService.sfexpressService(Runbow.TWS.Web.sfservice.sfexpressService request) {
            return base.Channel.sfexpressService(request);
        }
        
        public string sfexpressService(string arg0) {
            Runbow.TWS.Web.sfservice.sfexpressService inValue = new Runbow.TWS.Web.sfservice.sfexpressService();
            inValue.Body = new Runbow.TWS.Web.sfservice.sfexpressServiceBody();
            inValue.Body.arg0 = arg0;
            Runbow.TWS.Web.sfservice.sfexpressServiceResponse retVal = ((Runbow.TWS.Web.sfservice.IService)(this)).sfexpressService(inValue);
            return retVal.Body.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Runbow.TWS.Web.sfservice.sfexpressServiceResponse> Runbow.TWS.Web.sfservice.IService.sfexpressServiceAsync(Runbow.TWS.Web.sfservice.sfexpressService request) {
            return base.Channel.sfexpressServiceAsync(request);
        }
        
        public System.Threading.Tasks.Task<Runbow.TWS.Web.sfservice.sfexpressServiceResponse> sfexpressServiceAsync(string arg0) {
            Runbow.TWS.Web.sfservice.sfexpressService inValue = new Runbow.TWS.Web.sfservice.sfexpressService();
            inValue.Body = new Runbow.TWS.Web.sfservice.sfexpressServiceBody();
            inValue.Body.arg0 = arg0;
            return ((Runbow.TWS.Web.sfservice.IService)(this)).sfexpressServiceAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Runbow.TWS.Web.sfservice.expressServiceForRouteLabelResponse Runbow.TWS.Web.sfservice.IService.expressServiceForRouteLabel(Runbow.TWS.Web.sfservice.expressServiceForRouteLabel request) {
            return base.Channel.expressServiceForRouteLabel(request);
        }
        
        public string expressServiceForRouteLabel(string arg0) {
            Runbow.TWS.Web.sfservice.expressServiceForRouteLabel inValue = new Runbow.TWS.Web.sfservice.expressServiceForRouteLabel();
            inValue.Body = new Runbow.TWS.Web.sfservice.expressServiceForRouteLabelBody();
            inValue.Body.arg0 = arg0;
            Runbow.TWS.Web.sfservice.expressServiceForRouteLabelResponse retVal = ((Runbow.TWS.Web.sfservice.IService)(this)).expressServiceForRouteLabel(inValue);
            return retVal.Body.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Runbow.TWS.Web.sfservice.expressServiceForRouteLabelResponse> Runbow.TWS.Web.sfservice.IService.expressServiceForRouteLabelAsync(Runbow.TWS.Web.sfservice.expressServiceForRouteLabel request) {
            return base.Channel.expressServiceForRouteLabelAsync(request);
        }
        
        public System.Threading.Tasks.Task<Runbow.TWS.Web.sfservice.expressServiceForRouteLabelResponse> expressServiceForRouteLabelAsync(string arg0) {
            Runbow.TWS.Web.sfservice.expressServiceForRouteLabel inValue = new Runbow.TWS.Web.sfservice.expressServiceForRouteLabel();
            inValue.Body = new Runbow.TWS.Web.sfservice.expressServiceForRouteLabelBody();
            inValue.Body.arg0 = arg0;
            return ((Runbow.TWS.Web.sfservice.IService)(this)).expressServiceForRouteLabelAsync(inValue);
        }
    }
}
